In [2]:
numbers = [1,2,3,4,5]
print(numbers)

In [1]:
import numpy as np

In [4]:
array = np.array(numbers)

In [5]:
print(array)

[1 2 3 4 5]


In [6]:
doubled = array * 2
print(doubled)

[ 2  4  6  8 10]


In [7]:
zeroes = np.zeros((2,3))

In [8]:
print(zeroes)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
ones = np.ones(3)
print(ones)

[1. 1. 1.]


In [12]:
range_array = np.arange(0,10,3)
print(range_array)

[0 3 6 9]


In [15]:
num_array = np.arange(0,10)
print(num_array)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
fours = np.ones((4,4))
print(fours)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
linespace = np.linspace(0,1,5)
print(linespace)

[0.   0.25 0.5  0.75 1.  ]


In [31]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(matrix[0,1])

2


In [35]:
print(matrix[:,1])

[2 5 8]


In [36]:
num_array = np.arange(1,11)
print(num_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [39]:
print(num_array[0:5])

[0 1 2 3 4]


getting the first 2 rows

In [58]:
print(matrix[:2,:])

[[1 2 3]
 [4 5 6]]


From the matrix above, extract the bottom-right 2×2 sub-matrix.

In [63]:
bottom_right = matrix[1:,1:]
print(bottom_right)

[[5 6]
 [8 9]]


In [68]:
array_12 = np.arange(1,13)
print(array_12)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [72]:
array12_shaped = array_12.reshape(3,4)
print(array12_shaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [80]:
mid_cols = array12_shaped[:,1:3]
print(mid_cols)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [81]:
flattened = mid_cols.ravel()
print(flattened)

[ 2  3  6  7 10 11]


In [84]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

print(a)
print(b)

[1 2 3 4]
[10 20 30 40]


In [85]:
print(a+b)

[11 22 33 44]


In [102]:
a = np.array([5,10,15])
b = np.array([2,4,6])

In [94]:
print(a+b)

[5, 10, 15, 2, 4, 6]


In [106]:
cube = a**3
print(cube)

[ 125 1000 3375]


In [109]:
Broad = np.array([1,2,3,4,5])

#Broadcasting: stretching and applying the action across each item
# ie.[10,10,10,10,10]
# map vs broadcast?


print(Broad + 10)

[11 12 13 14 15]


Excercise: Multiply an array [2, 4, 6, 8] by 0.5.<br>
Create a 3×3 matrix and add np.array([1, 2, 3]) to it.<br>
Create a 2×3 matrix and add 10 to all elements.<br>

In [121]:
array_2 = np.array([2,4,6,8])
print(array_2*0.5)

[1. 2. 3. 4.]


In [135]:
matrix_three = np.arange(1,10).reshape((3,3))
print(matrix_three)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [136]:
print(np.array([1,2,3]) + matrix_three) 

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [144]:
import time

size=10_000_000

list_1 = list(range(size))
start = time.time() #time is a function

#we're creating a loop and looping over that list, then print)
list_2 = [x * 2 for x in list_1]
print('python array time',time.time() - start) #time just tells us how long it took to multiply the list by 2)

python array time 0.5877499580383301


In [140]:
numpy_1 = np.arange(size) # <- setting list size
start_1 = time.time()
numpy_2 = numpy_1 * 2 #<- the action
print('Numpy array time:', time.time() - start_1)

Numpy array time: 0.0017788410186767578


In [145]:
dice = np.random.randint(1,7, size=10)
print(dice)

[2 1 2 6 5 4 2 2 3 1]


Exercise<br>
Generate 20 dice rolls and find the min and max.<br>
Create an array of 10 random floats between 0 and 10. - Why do we have to use uniform <br>
Generate 1000 samples from a normal distribution and inspect the first 10.<br>

In [155]:
rolls_20 = np.random.randint(1,7, size = 20)
print(rolls_20)
dice_min = np.min(rolls_20,)
dice_max = np.max(rolls_20)
print('min value:', dice_min)
print('max value:', dice_max)

[4 5 6 6 1 1 2 3 2 6 3 5 2 5 6 6 5 1 1 6]
min value: 1
max value: 6


In [156]:
rand_floats = np.random.uniform(0,10, size = 10)
print(rand_floats)

[9.21412779 1.14740329 6.87520278 2.99221038 0.74875873 4.78879776
 0.73238163 8.33317294 2.61622087 0.53380368]


In [154]:
rand_dist= np.random.randn(1000)
print(rand_dist[0:10])

[-0.71149111 -0.20300748  1.3023775  -0.10348481  0.1729194  -0.68223039
  0.76071209  1.72150702  0.66112368  0.47744067]


In [157]:
stats_arr = np.array([1,2,3,4,5,6,7,8,9,10])

print('sum = ', np.sum(stats_arr))
print('mean = ', np.mean(stats_arr))
print('median = ', np.median(stats_arr))
print('stand = ', np.std(stats_arr))

sum =  55
mean =  5.5
median =  5.5
stand =  2.8722813232690143


Exercises<br>
Compute statistics for the dice rolls you generated and print them <br>
Create an array of 50 random integers between 10 and 100 and compute mean, median, and standard deviation, print them all out<br>

In [163]:
print('roll20 sum =', np.sum(rolls_20))
print('roll20 mean =', np.mean(rolls_20))
print('roll20 median =', np.median(rolls_20))
print('roll20 stand =', np.std(rolls_20))

roll20 sum = 76
roll20 mean = 3.8
roll20 median = 4.5
roll20 stand = 1.9646882704388502


In [166]:
rand_50 = np.random.randint(10,101,50)
print(rand_50)
print('50 sum =', np.sum(rand_50))
print('50 mean =', np.mean(rand_50))
print('50 median =', np.median(rand_50))
print('50 stand =', np.std(rand_50))

[62 70 99 94 93 93 81 16 73 39 35 42 10 77 37 44 95 30 82 90 62 59 99 65
 59 29 18 20 35 84 91 39 18 98 96 36 28 97 19 60 49 36 30 18 38 67 68 19
 79 29]
50 sum = 2807
50 mean = 56.14
50 median = 59.0
50 stand = 28.22340163764814


In [167]:
stack_1 = np.array([1,2,3])
stack_2 = np.array([4,5,6])

print(stack_1)
print(stack_2)

[1 2 3]
[4 5 6]


In [170]:
#vstack = vertical stack, hstack = horizontal stack
vstacked = np.vstack([stack_1,stack_2])
print(vstacked)

[[1 2 3]
 [4 5 6]]


Exercise<br>
Create a 1D array of 16 random integers and reshape it to 4×4. <br>
Create two new arrays manually using np.array. Stack them two 2×2 arrays both vertically and horizontally. <br>
Generate 2 sets of 5 dice rolls. Stack them into a 2×5 array.<br>

In [189]:
rand_16 = np.random.randint(1,16,16).reshape(4,4)
print(rand_16)

[[ 9  7  2  5]
 [ 2  5 12 12]
 [12 13 11 13]
 [15  4 13  8]]


In [190]:
top_arr = np.array([[1,2,3]])
low_arr = np.array([[4,5,6]])
v_stk = np.vstack([top_arr, low_arr])
h_stk = np.hstack([top_arr, low_arr])
print(v_stk, h_stk)

[[1 2 3]
 [4 5 6]] [[1 2 3 4 5 6]]


In [188]:
dice_1 = np.random.randint(1,7, size = 5)
dice_2 = np.random.randint(1,7, size = 5)
print(dice_1,dice_2)
v_dice_stk = np.vstack((dice_1, dice_2))
h_dice_stk = np.hstack((dice_1, dice_2))
print(v_dice_stk)
print('h dice stack',h_dice_stk)

[1 5 1 5 5] [2 5 1 6 2]
[[1 5 1 5 5]
 [2 5 1 6 2]]
h dice stack [1 5 1 5 5 2 5 1 6 2]
